### ISSUE TITLE
Use new service-services-service endpoint

### ISSUE THREAD

**Issue by kvisscher** [springtreesolutions/eva-tester#7]
Instead of GETting `/services` do a `POST` to  `/message/GetAvailableServices` and for the details `POST` to `/message/GetAvailableServiceDetails`

**Comment by realappie** [comment]
NOT A BUG

**Comment by realappie** [comment]
Closed by https://github.com/springtreesolutions/eva-tester/commit/a5caa7827a1061e6bb8920cc29e1666a2072b2df
